USE [master]
GO

/****** Object:  Database [LOGDB]    Script Date: 06/07/2013 19:57:25 ******/
CREATE DATABASE [LOGDB] ON  PRIMARY 
( NAME = N'LOGDB', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL10_50.SQLEXPRESS\MSSQL\DATA\LOGDB.mdf' , SIZE = 2048KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'LOGDB_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL10_50.SQLEXPRESS\MSSQL\DATA\LOGDB_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [LOGDB] SET COMPATIBILITY_LEVEL = 100
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [LOGDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [LOGDB] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [LOGDB] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [LOGDB] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [LOGDB] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [LOGDB] SET ARITHABORT OFF 
GO

ALTER DATABASE [LOGDB] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [LOGDB] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [LOGDB] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [LOGDB] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [LOGDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [LOGDB] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [LOGDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [LOGDB] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [LOGDB] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [LOGDB] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [LOGDB] SET  DISABLE_BROKER 
GO

ALTER DATABASE [LOGDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [LOGDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [LOGDB] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [LOGDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [LOGDB] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [LOGDB] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [LOGDB] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [LOGDB] SET  READ_WRITE 
GO

ALTER DATABASE [LOGDB] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [LOGDB] SET  MULTI_USER 
GO

ALTER DATABASE [LOGDB] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [LOGDB] SET DB_CHAINING OFF 
GO

